// flow-typed signature: a7bde7b1358440e019e879caabdba4da
// flow-typed version: <<STUB>>/rosie_v1.6.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rosie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rosie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rosie/src/rosie' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rosie/src/rosie.js' {
  declare module.exports: $Exports<'rosie/src/rosie'>;
}
