// flow-typed signature: 7e1c74f5a8af37104bc2538f9943944a
// flow-typed version: <<STUB>>/sanitize.css_v4.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
