// flow-typed signature: 7f8282c27dbac12794c9129dd811e325
// flow-typed version: <<STUB>>/warning_v3.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'warning'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'warning' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'warning/browser' {
  declare module.exports: any;
}

declare module 'warning/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'warning/browser.js' {
  declare module.exports: $Exports<'warning/browser'>;
}
declare module 'warning/warning.js' {
  declare module.exports: $Exports<'warning/warning'>;
}
